import { Course } from "@/types/explore";

export const COURSES: Course[] = [
    {
        id: 1,
        title: "Full-Stack Web Development with Next.js",
        description:
            "Master modern web development from scratch. Build production-ready apps using Next.js 14, TypeScript, Prisma, and Tailwind CSS.",
        category: "Programming",
        level: "Intermediate",
        duration: "42 hours",
        rating: 4.9,
        students: 12400,
        instructor: "Alex Carter",
        tags: ["Next.js", "TypeScript", "React"],
    },
    {
        id: 2,
        title: "Python for Data Science & Machine Learning",
        description:
            "Learn Python, NumPy, Pandas, and Scikit-learn to build powerful ML models and visualize data like a pro.",
        category: "Data Science",
        level: "Beginner",
        duration: "38 hours",
        rating: 4.8,
        students: 21000,
        instructor: "Dr. Priya Nair",
        tags: ["Python", "ML", "Pandas"],
    },
    {
        id: 3,
        title: "UI/UX Design Mastery with Figma",
        description:
            "Design stunning digital products. Cover user research, wireframing, prototyping, and handoff — entirely in Figma.",
        category: "Design",
        level: "Beginner",
        duration: "24 hours",
        rating: 4.7,
        students: 8900,
        instructor: "Sofia Reyes",
        tags: ["Figma", "Wireframing", "Prototyping"],
    },
    {
        id: 4,
        title: "Advanced Algorithms & System Design",
        description:
            "Crack top-tier tech interviews. Deep-dive into data structures, Big-O analysis, dynamic programming, and system design at scale.",
        category: "Programming",
        level: "Advanced",
        duration: "55 hours",
        rating: 4.9,
        students: 6700,
        instructor: "Michael Zhao",
        tags: ["Algorithms", "DSA", "System Design"],
    },
    {
        id: 5,
        title: "Digital Marketing & Growth Strategy",
        description:
            "Drive real business growth with SEO, paid ads, email funnels, and conversion optimization techniques used by top brands.",
        category: "Marketing",
        level: "Intermediate",
        duration: "18 hours",
        rating: 4.6,
        students: 15300,
        instructor: "Emma Davis",
        tags: ["SEO", "Ads", "Funnels"],
    },
    {
        id: 6,
        title: "Entrepreneurship: Building a Startup from Zero",
        description:
            "Validate your idea, build an MVP, raise funding, and scale — everything you need to launch your first startup.",
        category: "Business",
        level: "Beginner",
        duration: "20 hours",
        rating: 4.8,
        students: 9800,
        instructor: "James Okoro",
        tags: ["Startup", "MVP", "Funding"],
    },
    {
        id: 7,
        title: "Photography & Lightroom Editing Masterclass",
        description:
            "Go from amateur to professional. Learn composition, lighting theory, and post-processing with Adobe Lightroom.",
        category: "Photography",
        level: "Beginner",
        duration: "16 hours",
        rating: 4.7,
        students: 4500,
        instructor: "Chloe Martin",
        tags: ["Lightroom", "Composition", "Editing"],
    },
    {
        id: 8,
        title: "Cloud Architecture with AWS & Terraform",
        description:
            "Architect and deploy resilient, cost-optimized cloud infrastructure on AWS using Infrastructure as Code with Terraform.",
        category: "Programming",
        level: "Advanced",
        duration: "48 hours",
        rating: 4.9,
        students: 5200,
        instructor: "Omar Shaikh",
        tags: ["AWS", "Terraform", "DevOps"],
    },
    {
        id: 9,
        title: "Business Analytics with Excel & Power BI",
        description:
            "Turn raw data into impactful business decisions. Master pivot tables, dashboards, and Power BI reports.",
        category: "Business",
        level: "Intermediate",
        duration: "22 hours",
        rating: 4.5,
        students: 11200,
        instructor: "Laura Kim",
        tags: ["Excel", "Power BI", "Analytics"],
    },
];
